### ISSUE TITLE
Timezone config of plots

### ISSUE THREAD

**Issue by Harold2017** [flask-dashboard/Flask-MonitoringDashboard#123]
Hi, i think adding a timezone selection may be better for displaying time data maps. Most direct but not the best way can be adding a selection field in date form. Wish you have interest in this small issue XD

**Comment by mircealungu** [comment]
Wouldn't it be better to have one global dashboard setting: My Timezone which would transform all the times to the desired user timezone? Dates and times would be saved on the server in UTC and on the client side in whatever timezone the user has chosen.

**Comment by FlyingBird95** [comment]
I've created a branch for this: https://github.com/flask-dashboard/Flask-MonitoringDashboard/tree/issue123
The configuration already works, but I'm not able so far to adjust the heatmap with the correspondig timezone.

But I guess that this implementation will lead to the desired solution. @Harold2017 You can also clone from this branch to continue working on!

Patrick

**Comment by Harold2017** [comment]
Hi Patrick,

I just completed the database storage one in last [commit](https://github.com/flask-dashboard/Flask-MonitoringDashboard/pull/125) and make a simple trial of setting cookie [here](https://github.com/Harold2017/tests/blob/master/dashboard/test_session.pyl). And before that, i tried to store timezone info into user's config file but failed.. I found sometimes i cannot find the config file from config.file_path attr but when i use hasattr(config, 'filepath') i got true.. It is very strange so i delete that commit XD
I will try later with your solution~
Thanks!

Harold
