### ISSUE TITLE
per-version performance

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#135]
folks, is this a bug or a feature?
the versions are sorted based on their hashes not chronologically... 

<img width="320" alt="screenshot 2018-05-11 22 29 40" src="https://user-images.githubusercontent.com/464519/39945473-df0d83cc-556a-11e8-94db-e5be0e9f2dd3.png">

**Comment by bogdanp05** [comment]
I agree it makes more sense to have them ordered by date. I implemented this in 4896c8ac8b1b130c2da087105a37811d4f2cdf86 and now it looks like this: 
![selection_155](https://user-images.githubusercontent.com/7281856/39955536-ab53d28c-55d0-11e8-8ce2-fa5445bb8343.png)
Notice that version 1.5 would have appeared before 2.0 in the old version, but now they are sorted by date.

**Comment by mircealungu** [comment]
nice.
