### ISSUE TITLE
Overview table: saving sorting criterion / or make decreasing order of hits default

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#137]
1. Saving sorting criterion would be really nice to have.

2. Alternatively, simpler, and anyway better than what we have now is making the default ordering 'decreasing number of hits'. 

Personally I find myself always sorting in decreasing order of overall number of hits. I care about the most used API endpoints first. 

-- 

In any case, anything is better than alphabetical: alphabetical is good for telephone books, not for software systems. I've even wrote an entire paper about this once :) 

https://www.researchgate.net/publication/288448275_Overthrowing_the_Tyranny_of_Alphabetical_Ordering_in_Documentation_Systems

**Comment by FlyingBird95** [comment]
Implemented in #138
