### ISSUE TITLE
Add the possibility to define a prefix for table names

### ISSUE THREAD

**Issue by eapetitfils** [flask-dashboard/Flask-MonitoringDashboard#151]
Adding a prefix would allow the possibility to integrate the table into the same database as the rest of the Flask application. The prefix can be defined by default as `None` and if the config file defines one, then the `__tablename__` variables in `database.__init__.py` can prepend it with an underscore.

**Comment by FlyingBird95** [comment]
Really good idea!

This is something that will be implemented in version 2.0.0. You can already have a look at this version in https://github.com/flask-dashboard/Flask-MonitoringDashboard/tree/v2.0.0 (Note, that the branch is not stable yet). 

It approximately takes 2-3 weeks before v2.0.0 will be released, but we'll let you know by then.

Patrick

**Comment by bogdanp05** [comment]
Implemented in #164
