### ISSUE TITLE
execution_time in TestEndpoint

### ISSUE THREAD

**Issue by FlyingBird95** [flask-dashboard/Flask-MonitoringDashboard#158]
<img width="514" alt="screen shot 2018-06-08 at 10 25 29" src="https://user-images.githubusercontent.com/17162650/41147290-4e394dc0-6b06-11e8-9ab5-dae919764f96.png">

How can the 'execution_time' in TestEndpoint be an integer?

And maybe rename to 'duration' to be consistent with Request

**Comment by kloostert** [comment]
This is because execution_time is in milliseconds. 
But I will gladly change it to float, such that even more precision is added. 
Renamed it to duration as well. 
(#160)
