### ISSUE TITLE
strange values in request duration

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#174]
can you spot them? :) 

<img width="1154" alt="screenshot 2018-06-20 19 57 50" src="https://user-images.githubusercontent.com/464519/41675913-4e015dbc-74c4-11e8-8633-0cb0afd461d0.png">

**Comment by FlyingBird95** [comment]
This is a known bug (internally), but we haven't been able to fix this yet

**Comment by FlyingBird95** [comment]
I've created a Stackoverflow question for this: https://stackoverflow.com/questions/50958871/import-ordering-for-custom-js-and-datatables-with-jquery
