### ISSUE TITLE
Rename blueprint

### ISSUE THREAD

**Issue by iurisilvio** [flask-dashboard/Flask-MonitoringDashboard#182]
Blueprint `dashboard` is too common. I think it will be conflict a lot. Probably `monitoringdashboard` is a better blueprint name.

**Comment by FlyingBird95** [comment]
Hi iurisilvio,

It's indeed true that `dashboard` is a common name for a Flask blueprint. However, this is a decision from the start of the project, and changing the blueprint takes quite a lot of effort.

If there are more people complaining about this, we'll consider changing the blueprint name to `monitoringdashboard`, or `fmd_dashboard`.

Thanks again for discussing this with us!

Patrick
