### ISSUE TITLE
Why I cannot configure it from program code? Also, can I change engine?

### ISSUE THREAD

**Issue by DanGSun** [flask-dashboard/Flask-MonitoringDashboard#188]
I already have Flask app. There is configured Flask-Login, Flask-SQLAlchemy. I don't want to reconstruct my application. Also we have about 5 administrators. And I should have one public account for them all?
Thank you, if you find solution for this problem

**Comment by mircealungu** [comment]
Sorry, what do you mean by "reconstruct my application"?

**Comment by DanGSun** [comment]
I already have User Managment system and big user DB. I don't want to use another authentication system-- -----------------------------------------С уважением, Даниил Горлов,лидер GameDev12 Studio,E-Mail:president@gamedev12.ruDanGSun@yandex.ruСоциальные сети:vk.com/DanGSun ------------------------------------------Sincerely, DaniIl Gorlov,the leader of GameDev12 StudioE-Mail Adresses:president@gamedev12.ruDanGSun@yandex.ruSocial networks:vk.com/DanGSun03.09.2018, 17:06, "Mircea Filip Lungu" <notifications@github.com>:Sorry, what do you mean by "reconstruct my application"?

**Comment by mircealungu** [comment]
DanGSun, at the moment we do not have the manpower to integrate with external user authentication systems. For now I'll close this issue.
