### ISSUE TITLE
Can I get response values as well?

### ISSUE THREAD

**Issue by sodaliAyran** [flask-dashboard/Flask-MonitoringDashboard#196]
Hi guys, 
I was just checking out your documentation and I saw that you can get request values but can I also log response from my web service?

Let me explain with an example:

In my website there are some demo pages which users can enter texts.
After they enter a text I take it and send it to my web service. That gives me a response and I print a result back to the user.

What I want to do is log the entire process. Everything including the text entered by user and the response from my web service.

Can I do this easily using your application or do I need to customize a lot of things?

**Comment by bogdanp05** [comment]
Hi @sodaliAyran,

I think [this doc page](https://flask-monitoringdashboard.readthedocs.io/en/master/functionality.html?highlight=group_by) could help. Basically, you could write your own `get_log_message()` function inside your application and pass it to the **group_by** configuration `dashboard.config.group_by = get_log_message`. Then the **Request** table of the dashboard database would hold your logs inside the **group_by** column. 

Hope this helps!

**Comment by sodaliAyran** [comment]
@bogdanp05 I will try it as soon as possible. Thank you.

**Comment by bogdanp05** [comment]
Hi @sodaliAyran, 

If you like FMD, it would help us a lot if you could
- fill this 5 minutes form: [https://goo.gl/forms/pgTd6EJ8lLU13xmC3](https://goo.gl/forms/pgTd6EJ8lLU13xmC3)
OR
- arrange a short (<15 min) (Skype/Zoom) video discussion with us in which you can tell us a bit about how you use the FMD, what you like and what new features you would like to see

Regards,
Bogdan
