### ISSUE TITLE
migrating from sqlite to mysql

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#199]
dear folks,

i want to migrate from sqlite to mysql without losing my data.
what solution would you recommend?

I see a series of solutions on SO[1], but they're all quite ugly it seems to me.

[1] https://stackoverflow.com/questions/18671/quick-easy-way-to-migrate-sqlite3-to-mysql

**Comment by bogdanp05** [comment]
Hi Mircea,
This article[1] seems to describe exactly what you are trying to do. 

[1] https://github.com/weewx/weewx/wiki/Transfer-from-sqlite-to-MySQL

**Comment by mircealungu** [comment]
Hi Bogdan,

This seems to work for that particular application's DB.

Is there any guarantee that it would work for the FMD DB?

Also, if I'm not mistaken, in the case of that app they have
an app specific migration tool. Maybe we could consider
something like this for the FMD?

Cheers,
M.

**Comment by mircealungu** [comment]
Thanks for the analysis Bogdan!
If you can do this next week it would be great!

Cheers,
M.
