### ISSUE TITLE
number of hits zero instead of one

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#201]
dear folks,

the daily and weekly counters seem to not register the hit which happened a few seconds ago. 

![screen shot 2018-10-26 at 11 56 57 am](https://user-images.githubusercontent.com/464519/47567343-9406d980-d92e-11e8-9512-dea0156bbcb8.png)

**Comment by FlyingBird95** [comment]
It's not a bug. This endpoint has a monitoring-level of 0. So, nothing is monitored, except for the last-requested endpoint

**Comment by mircealungu** [comment]
Ouch! Thanks for the fast reaction time @FlyingBird95 !

Will be evident when we move the monitoring level info in the main table ;)
