### ISSUE TITLE
add the pip command to the upgrade message?

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#206]
![screen shot 2019-01-09 at 2 44 07 pm](https://user-images.githubusercontent.com/464519/50903136-26daee80-141d-11e9-8d7a-8ae7d2b76314.png)

It would be nice if the message would include the following: 

> "To upgrade run the following on your server `pip install --upgrade flask_monitoringdashboard`"

**Comment by FlyingBird95** [comment]
Implemented in 2.1.0
