### ISSUE TITLE
View response codes

### ISSUE THREAD

**Issue by ecterun** [flask-dashboard/Flask-MonitoringDashboard#207]
It would be helpful to see the breakdown of response codes for endpoints.  Not only to see if something is behaving incorrectly, or if there is a need for some changes to the way the endpoint functions or additional documentation.

I know there is this [doc](https://flask-monitoringdashboard.readthedocs.io/en/master/functionality.html?highlight=group_by) for group_by, but if my understanding is correct we would need to set the group_by on top before the response code is set.

Let me know if i am not understanding setting the group_by functionality, or if I'm just missing something and this is already available somewhere.

**Comment by FlyingBird95** [comment]
Hi @ecterun,

you're indeed right about the group_by functionality.

Currently, there is no possibility to retrieve the response code of a request.

I think that this would be useful to implement in the future.

For now, if you really want to monitor response codes of endpoints, you can use [Sentry](https://docs.sentry.io/clients/python/), or send us a PR

Patrick

**Comment by mircealungu** [comment]
status codes are now available in the latest version under Status Code Distribution
