### ISSUE TITLE
allow change of monitoring level from Profile page?

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#219]
could be something to consider.
now i'm looking at the page, and thinking... i'd like to enable the profiler, but i have to go back to the home page.

![Screen Shot 2019-03-12 at 10 19 18 AM](https://user-images.githubusercontent.com/464519/54188654-789d0500-44b0-11e9-8d51-1fec657ccf3f.png)

**Comment by bogdanp05** [comment]
I agree, it would be more convenient to enable the profiler from the profiler page.
On a side note, you don't have to go to the overview page to change the monitoring level. You can do that from either of the first 5 endpoint-specific views, i.e Hourly API Utilization all the way to Per-User Performance. You just have to scroll down to "Endpoint details" and select a monitoring level, as seen below.

![image](https://user-images.githubusercontent.com/7281856/54191158-a33d8c80-44b5-11e9-82f4-552f4d84fce1.png)

**Comment by bogdanp05** [comment]
I added the Endpoint details in every view, so the monitoring level can be changed from anywhere.
This fix is in the development branch.
