### ISSUE TITLE
no monitoring level highlighted

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#220]
in an attempt to get rid of issue #218  i deleted all the tables in the DB and restarted the API. The tables are recreated, but there's no default monitoring level for none of the endpoints. is this on purpose or is it a bug? 

![Screen Shot 2019-03-12 at 10 21 10 AM](https://user-images.githubusercontent.com/464519/54188770-b39f3880-44b0-11e9-803f-380603fdd798.png)

**Comment by bogdanp05** [comment]
All the endpoints besides the first one (which I guess you changed manually) seem to be set to monitoring level 1, as was intended in the most recent version? Or did you set them to 1 manually too?

**Comment by mircealungu** [comment]
oops :)
it wasn't clear to me that that color is "enabled" as opposed
to the normal color progression between 0 and 2 !!! maybe
underline the selection? e.g. 

![Screen Shot 2019-03-12 at 11 45 16 AM](https://user-images.githubusercontent.com/464519/54194365-62954180-44bc-11e9-8deb-70c302915fe3.png)

**Comment by bogdanp05** [comment]
The fix (underline the selected monitoring level) is now on development branch.
