### ISSUE TITLE
After upgrading to version 2.1.2, no hits are detected anymore

### ISSUE THREAD

**Issue by nocrosstalk** [flask-dashboard/Flask-MonitoringDashboard#224]
Expected
After update Dashboard to version 2.1.2 keeps working, counting hits and collecting stats

Current behaviour
I upgraded dashboard to version 2.1.2, according to a message shown on the dashboard. The dashboard still shows up but no hits are recorded anymore. I deleted the sqlite database I use, no difference. A new database is created correctly though. Endpoints are shown correctly though.

Context
Flask version = 1.0.2

config ~
MONITOR_LEVEL=3
OUTLIER_DETECTION_CONSTANT=2.5
SAMPLING_PERIOD=20
ENABLE_LOGGING=True

**Comment by nocrosstalk** [comment]
I downgraded to version 2.0.7 and it works again.

**Comment by bogdanp05** [comment]
Hi @nocrosstalk! I was able to replicate the issue. It seems to be a race condition that occurs sometimes for monitoring levels 2 and 3. I'm assuming you also get this message in the logs:
```
No commit has been made, due to the following error: 'NoneType' object has no attribute 'id'
```

**Comment by nocrosstalk** [comment]
Forgot to check and now downgraded, sorry.

**Comment by bogdanp05** [comment]
Fixed with PR #225

**Comment by nocrosstalk** [comment]
Txs!

**Comment by bogdanp05** [comment]
Hi @nocrosstalk, 

If you like FMD, it would help us a lot if you could
- fill this 5 minutes form: [https://goo.gl/forms/pgTd6EJ8lLU13xmC3](https://goo.gl/forms/pgTd6EJ8lLU13xmC3)
OR
- arrange a short (<15 min) (Skype/Zoom) video discussion with us in which you can tell us a bit about how you use the FMD, what you like and what new features you would like to see

Regards,
Bogdan
