### ISSUE TITLE
Not working with Postgresql -> api/endpoints_hits

### ISSUE THREAD

**Issue by joshteng** [flask-dashboard/Flask-MonitoringDashboard#226]
**Describe the bug**
GET 'dashboard/api_performance' not working when using Postgresql.

Error from logs:
```
No commit has been made, due to the following error: (psycopg2.ProgrammingError) column "fmd_Endpoint.name" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "fmd_Endpoint".name AS "fmd_Endpoint_name", count("fm...
               ^

[SQL: SELECT "fmd_Endpoint".name AS "fmd_Endpoint_name", count("fmd_Request".endpoint_id) AS count_1 
FROM "fmd_Endpoint" JOIN "fmd_Request" ON "fmd_Endpoint".id = "fmd_Request".endpoint_id GROUP BY "fmd_Request".endpoint_id ORDER BY count("fmd_Request".endpoint_id) DESC]
(Background on this error at: http://sqlalche.me/e/f405)
``` 

**To Reproduce**
1. Go to dashboard/api_performance

**Screenshots**
![Screenshot](https://i.imgur.com/y6QLMbm.png)
![Log](https://i.imgur.com/Xwm16fF.png)

**Desktop:**
 - OS: Mac OS
 - Browser Chrome
 - Version 73.0.3683.86 (Official Build) (64-bit)

**Additional context**
This is the endpoint causing the error https://github.com/flask-dashboard/Flask-MonitoringDashboard/blob/master/flask_monitoringdashboard/views/endpoint.py#L64

Source of error in this function https://github.com/flask-dashboard/Flask-MonitoringDashboard/blob/master/flask_monitoringdashboard/database/endpoint.py#L168

**Comment by bogdanp05** [comment]
Hi @joshteng ! Thanks for reporting this bug. It had to do with a lack of compatibility between SQLite, MySQL, and Postgresql when it comes to SQL queries. I fixed it in PR #227 .

**Comment by bogdanp05** [comment]
Hi @joshteng !

If you like FMD, it would help us a lot if you could
- fill this 5 minutes form: [https://goo.gl/forms/pgTd6EJ8lLU13xmC3](https://goo.gl/forms/pgTd6EJ8lLU13xmC3)
OR
- arrange a short (<15 min) (Skype/Zoom) video discussion with us in which you can tell us a bit about how you use the FMD, what you like and what new features you would like to see

Regards,
Bogdan

**Comment by joshteng** [comment]
Left my feedback on the form! @bogdanp05

**Comment by joshteng** [comment]
@bogdanp05 Sorry for adding to this issue, I can't remember if I wrote it in the feedback form but the ability to filter and maybe compare API Performance by deploy versions would be really great. We mostly use FMD to refactor and improve response/execution time.

With regards to Heroku, I found another way to get the commit SHA https://devcenter.heroku.com/articles/dyno-metadata

**Comment by bogdanp05** [comment]
Thanks for the feedback @joshteng! 
At the moment, you can compare the per-version performance of individual endpoints, not the entire API at once. This might still prove quite useful for your workflow, though.

Regards,
Bogdan
