### ISSUE TITLE
[feature request] running the same API in multiple workers

### ISSUE THREAD

**Issue by databill86** [flask-dashboard/Flask-MonitoringDashboard#228]
**This is a feature request**
Is there any way we can run the monitoring dashboard in multiple brokers/workers with the same API using the same endpoints ? 
Let's say, we have two docker containers running the same API with the same endpoints, and each of these is running with multiple gunicorn workers. Can the monitoring dashboard collect all the metrics from the different workers without any conflict ?

Thank you.

**Comment by bogdanp05** [comment]
Hi @databill86 !

This should be possible already. As long the `DATABASE` url in the [configuration](https://flask-monitoringdashboard.readthedocs.io/en/master/configuration.html#database) is the same, the metrics  will be collected in the same tables.

On an unrelated topic, if you like FMD, it would help us a lot if you could
- fill this 5 minutes form: [https://goo.gl/forms/pgTd6EJ8lLU13xmC3](https://goo.gl/forms/pgTd6EJ8lLU13xmC3)
OR
- arrange a short (<15 min) (Skype/Zoom) video discussion with us in which you can tell us a bit about how you use the FMD, what you like and what new features you would like to see


Regards,
Bogdan

**Comment by databill86** [comment]
Hi @bogdanp05, 
Thank you, I will try that. 

I've filled the form. 

Regards,
