### ISSUE TITLE
Reporting 0 ms for all endpoints

### ISSUE THREAD

**Issue by TheodoreAD** [flask-dashboard/Flask-MonitoringDashboard#236]
First off, congratulations are in order for a great tool. This is an ideal solution for profiling without having access to the machine, which makes it great for use in kubernetes (my use case). 

Problem:

Endpoint run statistics are fine wrt number of hits, however they all report 0 ms execution time. 

The profiler only shows two rows for each hit, the route decorator and the route function, each reporting 0 ms execution time. 

Context:
- Browser OS: Windows 10 (latest updates) 
- Browser: Chrome (tested your demo without issues there) 
- FMD OS: CentOS 7.5 Docker container
- FMD Version: 2.1.0 and 2.1.4
- database string: sql:////tmp/flask_dashboard.db
- no other modifications to configuration (no config file used, db string set via dashboard.config directly) 
- Python: 3.6.2
- Flask: 1.0.2
- Gunicorn (started and configured via supervisord) 
- no errors in Gunicorn / Flask worker output

**Comment by bogdanp05** [comment]
Hi @TheodoreAD,

We're glad you like the Flask Monitoring Dashboard!

As for the issue, that is the expected behavior if your endpoint is very fast. The profiler of the FMD is statistical, not deterministic, meaning that it does not record every instruction executed, but only samples the stack trace with a given frequency and then infers where time is being spent. You can read more about the difference [here](https://docs.python.org/3/library/profile.html#what-is-deterministic-profiling). 
My guess is that the code you're trying to sample is faster than the sampling period of the profiler. 

Regards,
Bogdan

**Comment by TheodoreAD** [comment]
I have tried various scenarios, the latest being using apache bench for 30 tries on an endpoint that took between 25 and 30 seconds to respond each time. 

Seeing as how your playground example reacts to 200ms durations, I can't help but think I'm not either doing something right or there is some obscure bug.

Being able to get the profiling information for long running endpoints was the reason I was so excited about your project in the first place :)

**Comment by bogdanp05** [comment]
It does sound like an obscure bug that we've never dealt with before. Could you verify a few things for me? 

1. Just to make sure I get it right, you see in the profiler table something like this:
![image](https://user-images.githubusercontent.com/7281856/57635676-e7c5d100-75a7-11e9-94ac-c0f8fd2955c2.png)

but only with the first two lines and with the values of 0 ms?

2. Can you check what the duration for that endpoint should be? You can do this in the overview page by selecting the Median request duration button under the table.

3. Can you try different endpoints to see if the problem persists?

4. Is the profiler info collected in the database? You can check this in the CodeLine and StackLine tables.

**Comment by sizzlorox** [comment]
I'm also having this behavior.
I have checked the profile and it does not go through all of the stacktrace, although I can see these messages within my terminal.

`Can't get the stacktrace of the main thread. Stopping StacktraceProfiler`
`Can't get the stacktrace of the main thread.`

**Comment by bogdanp05** [comment]
Hi @sizzlorox, thanks for joining the conversation! Your logs are really helpful. It shows that the error can only stem from [this line.](https://github.com/flask-dashboard/Flask-MonitoringDashboard/blob/d1962a272c2c3d831cd51a8c086ec15d0663142e/flask_monitoringdashboard/core/profiler/stacktraceProfiler.py#L55)

Unfortunately, as I'm unable to replicate it, there's not much I can do to fix it. I just added some extra logs in the development branch to print the thread ids. If you think you might have a solution that works, send us a PR and we'll be happy to accept it.

**Comment by sizzlorox** [comment]
@bogdanp05 It appears my project had an old version of Flask which caused flask_monitoringdashboard to install an older version. After removing the dashboard and updating Flasks version, flask_monitoringdashboard was installed with the latest version and has resolved the issue!

Thank you!
