### ISSUE TITLE
Version 2.1.0 can not Point Configuration file

### ISSUE THREAD

**Issue by jualy007** [flask-dashboard/Flask-MonitoringDashboard#244]
**Describe the bug**
Version 2.1.0 can not Point Configuration file, the init_from method do not read  Configuration file, but in master branch, init_from method have read Configuration file step.

**Comment by bogdanp05** [comment]
Hi @jualy007! Can you upgrade to version 2.1.4? Is the problem still present there?

**Comment by jualy007** [comment]
> Hi @jualy007! Can you upgrade to version 2.1.4? Is the problem still present there?

I have try to install 2.1.1~2.1.4 version many times, but always failed. I can only install version 2.1.0.

**Comment by bogdanp05** [comment]
What error do you get after running `pip install --upgrade flask_monitoringdashboard`?
