### ISSUE TITLE
Display referer sources and IP geolocations

### ISSUE THREAD

**Issue by void4** [flask-dashboard/Flask-MonitoringDashboard#246]
One of the more useful features of Google Analytics is being able to see where your users come from, both physically and virtually. Would it be possible to build this into the Monitoring Dashboard?

Storing the referer will require a new database field if I understand the schema correctly.

Edit: Okay, I just managed to create some nice plots with geolite2, pandas and plotly.express' [Chloropleth Maps](https://plot.ly/python/choropleth-maps/). Would these be too heavy dependencies?

**Comment by bogdanp05** [comment]
Hi @void4! At the moment, the Flask Monitoring Dashboard does not store any personal information about the users of the monitored web application and we intend to keep it that way.  We don't want to deal with data privacy regulations.

You can use the  [group by](https://flask-monitoringdashboard.readthedocs.io/en/latest/functionality.html#monitoring-level-1-performance-and-utilization-monitoring) functionality to retrieve the users' locations yourself and store them in the FMD database.
