### ISSUE TITLE
Proposed Feature: Extending configuration file to allow custom navbar brand

### ISSUE THREAD

**Issue by minelminel** [flask-dashboard/Flask-MonitoringDashboard#247]
# Background
I am a regular user of the package and have come to depend on it for many of my projects. However, I often find the need to constantly fork the repo only to make small changes regarding the UI, increasing the complexity of the deployment cycle since this involves breaking the cardinal rule of "don't repeat yourself."

# Problem
The most consistent changes I find myself making are modifications to the login page, dashboard navbar logo text, and Instructables scattered throughout the templates.

# Proposal
Allow the following items to be declarable via the config.cfg file:
- NAVBAR_LOGO_TEXT `<str>`
    - allow the user to specify a string to replace "FLASK MONITORING DASHBOARD" in the dashboard navbar.
- SHOW_LOGIN_GRAPHIC `<bool>`
    - allow the user to disable rendering the default logo image displayed above the form in the login page
- SHOW_INSTRUCTABLE_TEXT `<bool>`
    - allow the user to disable displaying "Automatically monitor the evolving performance...." in the navbar, as well as "Click HERE to read advanced documentation" in the footer.

I would enable this in such a way that preserves backward compatibility, whereas if the above variables are not declared, the package would simply function as it currently does.

I have built this functionality into my own version of the package and use it regularly, however, the deployment inconvenience is increased due to the fact that I must now include my own .whl in order to integrate it into a project. I have contemplated uploading my version to PyPI to simplify the inclusion process, however, I feel this is a rather petty change that does not warrant its own secondary distribution mechanism. I would much rather contribute to the existing framework in the hope that others may find this functionality useful.

# Moving Forward
My main purpose of this post is to try and gauge the level of interest in this addition among both maintainers and users of this package. If others deem it a worthy inclusion, I will finish the process of disentangling the above features from my custom repo, writing proper tests, and submitting a pull request.

**Comment by bogdanp05** [comment]
Hi, Micheal! It's great to hear you like the project. 

Your proposed changes only influence small parts of the UI. I never thought about them and I don't know how many people, other than yourself, would be using the new configuration. 

On the other hand, your changes don't break anything either, as long as the default values stay the same. So, if you think they will ease your deployment cycle, then go ahead and submit a PR to the development branch. Please also update the [docs](https://github.com/flask-dashboard/Flask-MonitoringDashboard/blob/master/docs/configuration.rst#the-content-of-the-configuration-file) to reflect the changes you made.

**Comment by mircealungu** [comment]
closed for lack of activity.
