### ISSUE TITLE
Sorting is broken for the first two columns

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#257]
**Describe the bug**
Sorting seems to be broken for Number of hits (Today + Last 7 Days) in 3.0.2. For all the other columns it works. 

**To Reproduce**
1. Login
2. Click on 'Today'

**Comment by ayanlee** [comment]
The cause of this seems to be the error messages. The error messages seem to change those columns from numeric sorting to lexicographical sorting

**Comment by mircealungu** [comment]
@DeJonge00 - can you look into this and probably add the red text as a CSS property as opposed to actual text in the table cell? Then sorting should work again.

**Comment by mircealungu** [comment]
Fixed in https://github.com/flask-dashboard/Flask-MonitoringDashboard/commit/4b975a23d6595f2f840b6c9c01dbf9812c1e0a9d
