### ISSUE TITLE
Error when running from Docker image

### ISSUE THREAD

**Issue by ezeev** [flask-dashboard/Flask-MonitoringDashboard#261]
I have added flask-monitoringdashboard to my flask app. It runs great on my machine until I containerize it. I have a Dockerfile that uses an alpine base image. Everything installs and builds properly - but when I run the app I get this error:

```
ImportError: cannot import name 'config' from 'flask_monitoringdashboard' (/home/flask/venv/lib/python3.7/site-packages/flask_monitoringdashboard/__init__.py)
```

Has anyone seen this before or have any ideas? I don't understand why it would be able to import only when running in the container.

**Comment by mircealungu** [comment]
Hi @ezeev . 
How do you install FMD? Do you do it manually or automatically from a requirements.txt? 
How does your requirements.txt look like?

**Comment by ezeev** [comment]
Hi @mircealungu  - thanks for the quick reply.

I am installing from a requirements file. Here is my requirements and my Dockerfile:

requirements.txt:

```
alembic==1.0.5
amqp==2.5.1
appdirs==1.4.3
APScheduler==3.6.1
asn1crypto==0.24.0
astroid==2.1.0
attrs==18.2.0
Babel==2.7.0
bcrypt==3.1.5
beautifulsoup4==4.7.1
billiard==3.6.1.0
cached-property==1.5.1
cachetools==3.1.0
celery==4.3.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
Click==7.0
colorhash==1.0.2
configparser==4.0.2
coverage==4.5.2
cryptography==2.7
curlify==2.1.0
defusedxml==0.5.0
docker==3.7.3
docker-compose==1.24.1
docker-pycreds==0.4.0
dockerpty==0.4.1
docopt==0.6.2
facebook-business==4.0.6
facebookads==2.11.4
Flask==1.0.2
Flask-Bcrypt==0.7.1
Flask-Cors==3.0.7
Flask-Migrate==2.3.1
Flask-MonitoringDashboard==3.0.5
Flask-Script==2.0.6
Flask-SQLAlchemy==2.3.2
Flask-Testing==0.7.1
flower==0.9.3
google==2.0.1
google-auth==1.6.3
google-auth-oauthlib==0.2.0
googleads==17.0.0
idna==2.7
importlib-metadata==0.19
isodate==0.6.0
isort==4.3.4
itsdangerous==1.1.0
Jinja2==2.10
jsonschema==2.6.0
kombu==4.6.4
lazy-object-proxy==1.3.1
lxml==4.3.1
Mako==1.0.7
MarkupSafe==1.1.0
mccabe==0.6.1
numpy==1.17.2
oauthlib==3.0.1
paramiko==2.6.0
psutil==5.6.3
psycopg2==2.7.6.1
psycopg2-binary==2.7.6.1
pyasn1==0.4.5
pyasn1-modules==0.2.4
pycparser==2.19
PyJWT==1.7.1
pylint==2.2.2
PyNaCl==1.3.0
python-dateutil==2.7.5
python-editor==1.0.3
pytz==2018.9
PyYAML==4.2b4
redis==3.3.8
requests==2.20.1
requests-oauthlib==1.2.0
requests-toolbelt==0.9.1
rsa==4.0
simplejson==3.16.0
six==1.12.0
soupsieve==1.8
SQLAlchemy==1.2.15
suds-jurko==0.6
texttable==0.9.1
tornado==5.1.1
tzlocal==2.0.0
urllib3==1.24.1
vine==1.3.0
websocket-client==0.56.0
Werkzeug==0.14.1
wrapt==1.10.11
xmltodict==0.12.0
zeep==3.2.0
zipp==0.5.2
```

Dockerfile:

```
FROM python:3.7-alpine

RUN apk update && apk upgrade
RUN \
 apk add --no-cache libffi-dev gcc postgresql-libs libxml2-dev libxslt-dev python-dev make linux-headers && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev

RUN adduser -D flask

WORKDIR /home/flask

COPY requirements.txt requirements.txt
RUN python -m venv venv
RUN venv/bin/pip install -r requirements.txt
RUN venv/bin/pip install gunicorn

COPY project project
COPY tasks tasks
COPY manage.py manage.py
COPY boot.sh boot.sh
COPY client_secret.json client_secret.json
RUN chmod +x boot.sh

ENV FLASK_APP 'project/server'

RUN chown -R flask:flask ./
USER flask

EXPOSE 5000
```

**Comment by mircealungu** [comment]
Hi @ezeev!

I can't see anything that's obviously the problem here...
Can you give me the lines that are related to the binding of FMD on your application maybe?

Cheers,
M.

**Comment by ezeev** [comment]
Hi @mircealungu - thanks for helping!

I have these lines in an __init__.py file in the `project/server/` directory:

```python
import os

from flask import Flask
from flask_bcrypt import Bcrypt
from flask_sqlalchemy import SQLAlchemy
from flask_cors import CORS
import flask_monitoringdashboard

app = Flask(__name__)
flask_monitoringdashboard.bind(app)
```

**Comment by ezeev** [comment]
Again, this works fine in a virtual env on my mac. It only happens when I run it in a container. I haven't tried with different base images. It's driving me nuts that I can't find any obvious clues as to the cause.

**Comment by RuanMuller** [comment]
@ezeev - It may be a missing timezone setup in Alpine.

The real error may not be obvious depending on how your logging is configured, but it's possible that there is a preceding error coming from `tzlocal` not being able to determine the timezone. 

Try the following from your venv on the Docker image:
```
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tzlocal import get_localzone
>>> get_localzone()
<DstTzInfo 'local' STD-1 day, 16:00:00 STD>
>>>
```

If `DstTzInfo` is `local`, that's the likely issue.

`tzlocal` will check to see if `TZ` is set in the environment, so you could try setting the `TZ` environment variable directly with `docker run`:
```--env=TZ="UTC"```

The timezone can also be configured and set  in the Dockerfile for Alpine which requires `tzdata` to be installed first:
```
RUN apk add --no-cache tzdata
ENV TZ UTC
```

Incidentally the same issue occurs on WSL Ubuntu which also has no timezone configuration by default.

**Comment by ezeev** [comment]
This was exactly my problem @RuanMuller  - thanks for the help!
