### ISSUE TITLE
sorting seems to be broken for monitoring levels

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#264]
when i click on the Monitoring level table header, i'd expect to be able to sort the columns accordingly.

**Comment by FlyingBird95** [comment]
Isn't this related to #257 ?

**Comment by mircealungu** [comment]
in a way yes.
the good news is that #257 is solved in the latest version of #development 

the bad news is that the sorting on monitoring levels might be more complicated. 
i looked a bit into it, but i don't know angular. the following snippet in `overview.html` should allow sorting on that column too.

                    <td ng-click="$event.stopPropagation()" data-sort="{{ row.monitor }}">
                        <monitorlevel name="row.name" value="row.monitor" />
                    </td>

the complication arises from the fact that even after the change of a monitoring level the the table still sorts on the initial state of the table. i wonder if the effort is worth for this feature.

**Comment by mircealungu** [comment]
too complicated to fix at the moment.
