### ISSUE TITLE
Could I monitor sqlalchemy performance by flask-monitoringdashboard

### ISSUE THREAD

**Issue by SincerelyUnique** [flask-dashboard/Flask-MonitoringDashboard#269]
Because I want to see some bad sql in our system and their time spend.

**Comment by mircealungu** [comment]
Hi @SincerelyUnique 

That is a good question. 

If inside the endpoints that you are monitoring you use SQLAlchemy code, then you can learn about the performance bottlenecks by enabling the profiler for them. 

For a story of how I used the FMD to improve the performance of an endpoint that was depending on SQLAlchemy see this blog post: [Using a Performance Monitor to Illustrate the Power of DB Indexes
](https://mircealungu.github.io/post/18-09-07--db-indexes/ )

**Comment by SincerelyUnique** [comment]
I will see this blog post, thank you! @mircealungu
