### ISSUE TITLE
On docker, it's writing table definitions at flask_monitoringdashboard.db, but no stats

### ISSUE THREAD

**Issue by martinvergara** [flask-dashboard/Flask-MonitoringDashboard#270]
**Describe the bug**
I don't see any data when browsing /dashboard. I manage to see that some table definitions are written at flask_monitoringdashboard.db, but no endpoints routes or any kind of stats. 

**To Reproduce**
1. Build docker image with flask application on it
2. Start container
3. Go to /dashboard
4. No endpoints or any kind of stats are listed

Sorry for this short steps description, but I don't know what other steps are relevant

**Expected behavior**
I would expect to see stats, and I would expect some data to be written at flask_monitoringdashboard.db, besides data definitions.

**Screenshots**
![image](https://user-images.githubusercontent.com/11800410/68058888-40656380-fcd9-11e9-8379-371c7a5746df.png)

I'm not seeing any network trouble

![image](https://user-images.githubusercontent.com/11800410/68058933-6559d680-fcd9-11e9-97d2-aeaa26579bfc.png)

**Desktop:**
 - OS: LInux
 - Docker image: python:3.5-onbuild
-  WSGI server: waitress

**Additional context**
At first, "unable to open database file" error was appearing, and I couldn't even browse /dasboard. To solve this, I tried to manually create flask_monitoringdashboard.db file (empty). From that point, I could browse /dashboard. 
As I said, no endpoints are even listed, but I'm not seeing any error log!
This is only happening at production environment. It is hosted at AWS.

Thank you so much

**Comment by mircealungu** [comment]
Hi @martinvergara !

You should never have to create the DB by hand.
Are you sure that the configuration environment variable and corresponding config file are correctly setup? 

Have a look at this example of Dockerfile which configures the FMD to be deployed in a container for an example that works: 

https://github.com/zeeguu-ecosystem/Lineup/blob/1c4fd12638b200e0e1b3000e4fbe07b6a6301aeb/docker-files/zeeguu-api-core/Dockerfile#L54
