### ISSUE TITLE
usability issue: button should be moved to the top

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#271]
"Number of hits / Median request duration" should be in the title of the corresponding column

**Comment by bogdanp05** [comment]
Hey Mircea! Do you mean something like this?:

![image](https://user-images.githubusercontent.com/7281856/68814041-0badc080-0678-11ea-9c14-95c4f04788de.png)

**Comment by ayanlee** [comment]
Hi Bodgan! I was also looking at this issue, and came up with something like this:

![image](https://user-images.githubusercontent.com/24267722/68947044-bf1bcf80-07b4-11ea-96cd-a23cc9d40880.png)

What do you think?

**Comment by FlyingBird95** [comment]
Hi all,

Personally, I really like your idea @ayanlee .

I'm looking forward to see your PR.

Patrick

**Comment by bogdanp05** [comment]
Hey @ayanlee ! I actually like your design more than mine, so please feel free to submit a PR:)
