### ISSUE TITLE
Upgrade message is broken?

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#277]
![image](https://user-images.githubusercontent.com/464519/69723729-9ed80300-111a-11ea-98a3-c7a2c2efb472.png)

**Comment by ayanlee** [comment]
![image](https://user-images.githubusercontent.com/24267722/71190604-31387600-2285-11ea-828c-f3109ab6b7e0.png)

I think the issue might lie here. 

The logical operator should be ">", right?

I think response.data['dashboard-version']; returns a string, so my idea is to create a compare method  which takes two strings as input. What do you think?

**Comment by bogdanp05** [comment]
@ayanlee I encourage this fix! I figured that was the cause, but I was always too lazy to fix it myself, I just closed the notification:)

**Comment by mircealungu** [comment]
Nice find @ayanlee :)

**Comment by FlyingBird95** [comment]
This is now fixed, and is on the development-branch. Closing this issue
