### ISSUE TITLE
Colors for reporting

### ISSUE THREAD

**Issue by ayanlee** [flask-dashboard/Flask-MonitoringDashboard#279]
We could add colors to show what developments have been positive and what developments have been negative. I think this would make for a nice little improvement. :)

What do you think? @thejager 

![image](https://user-images.githubusercontent.com/24267722/69726739-70a9f180-1121-11ea-985b-ee762913f4f7.png)

**Comment by thejager** [comment]
That is cool :)

Let me know if I can help!

**Comment by ayanlee** [comment]
> That is cool :)
> 
> Let me know if I can help!

Hi Johan,  there is!

![image](https://user-images.githubusercontent.com/24267722/70243354-b7779700-1772-11ea-8e3c-c5aa3ef20c0e.png)
I've been trying to modify this if-statement for this solution, but I can't seem to make that work. I think I have to write JS to solve this, but I'm not sure how to interact with these elements.

Thank you for your help!

**Comment by thejager** [comment]
You want to change the looks of the complete `h4`, right? Then I think you should just conditionally assign a class to `h4`. Either give it e.g. `positive-report` or `negative-report` class, depending on `answer.percentual_diff`.

Have a look at this line:

https://github.com/flask-dashboard/Flask-MonitoringDashboard/blob/7bc72964ca134bf6e7c2952dc2d61f708386fcf2/flask_monitoringdashboard/static/pages/reporting.html#L62
