### ISSUE TITLE
Is a postgresql database compatible?

### ISSUE THREAD

**Issue by rileyhun** [flask-dashboard/Flask-MonitoringDashboard#285]
**Describe the bug**
I added a postgresql database on cloud-sql to the config file file, and it sets up the tables properly, but I run into the following error: 

```
No commit has been made, due to the following error: (psycopg2.errors.ForeignKeyViolation) insert or update on table "fmdOutlier" violates foreign key constraint "fmdOutlier_request_id_fkey"
DETAIL:  Key (request_id)=(1) is not present in table "fmdRequest".

```

**To Reproduce**
I added this block to config.cfg: 
```
[database]
TABLE_PREFIX=fmd
DATABASE=postgresql://<user>:<pass>@127.0.0.1:3306/<db_name>
```

**Expected behavior**
I ran this using the default sqlite path and it was working fine; it only results in an issue when using postgresql or mysql.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Chrome

**Comment by bogdanp05** [comment]
Hi Riley, thanks for reporting the issue! Compatibility issues with Postgresql and Mysql are a recurring problem. Even though we are using SQLAlchemy, which is supposed to abstract away the RDBMS, we learned over time that this isn't 100% and we have to manually patch bugs like these from time to time. I'll look into it at some point this week, but feel free to submit a PR if you fix the bug by then.

@team: we should really look into expanding the tests to include mysql and postgresql. Would this mean running the tests 3 times (sqlite, mysql, postgresql) or is there a smarter way?

**Comment by mircealungu** [comment]
@bogdanp05 Testing with the three backends seems like a good idea! I think that running the tests three times on integration should be "smart enough". Or?

**Comment by FlyingBird95** [comment]
Maybe this gist [1] can help us with configuring the travis configuration.

[1] https://gist.github.com/mceachen/2340726

**Comment by rileyhun** [comment]
Is the issue perhaps due to the fact that you are using a primary key as a foreign key in quite a few instances? Not sure if that's ideal. 

https://stackoverflow.com/questions/10982992/is-it-fine-to-have-foreign-key-as-primary-key

**Comment by bogdanp05** [comment]
@rileyhun The SO post you linked asks about using a **FK as a PK**. We never do that: https://flask-monitoringdashboard.readthedocs.io/en/latest/developing.html#data-layer .

As you correctly observed, we do use **PKs as FKs** basically everywhere. Which is how you do one-to-many relationships.

**Comment by mircealungu** [comment]
For now I'll close this issue because it seems to be fixed in https://github.com/flask-dashboard/Flask-MonitoringDashboard/pull/301/commits/8af334fe2394ee6f8faf27e955428680ffafc190.

However, @ayanlee  -- can you look into running the tests on Travis with all the DB backends, as @FlyingBird95 suggests above (see the gist that he shared).
