### ISSUE TITLE
[Proposal] Run the dashboard with non git project too

### ISSUE THREAD

**Issue by alessiosavi** [flask-dashboard/Flask-MonitoringDashboard#290]
It's possible to run the `Flask-MonitoringDashboard` for project that does not use `git` as version system?

Let's assume the following scenario:

- Tool that is shipped as Docker container
- .dockerignore file for avoid to ship the `.git/` folder.

With the introduction of `github actions`, automatic test using this new feature is not possible for project that use the `FMD`, cause the `.git/` folder will not be copied.

In this case, the `Flask-MonitoringDashboard` will raise the following error:

```text
File "main.py", line 52, in <module>
    dashboard.config.init_from(file=CFG["dashboard"]["config_file"])
  File "/usr/local/lib/python3.8/site-packages/flask_monitoringdashboard/core/config/__init__.py", line 119, in init_from
    self.version = parse_version(parser, 'dashboard', self.version)
  File "/usr/local/lib/python3.8/site-packages/flask_monitoringdashboard/core/config/parser.py", line 24, in parse_version
    git_file = (open(os.path.join(git, 'HEAD')).read().rsplit(': ', 1)[1]).rstrip()
FileNotFoundError: [Errno 2] No such file or directory: '.git/HEAD'
```

Proposal:
- Let the dashboard work without knowing the version of the software in case of `.git/` folder not found 
- Initialize a new "fake" repository

**Comment by mircealungu** [comment]
Hi @alessiosavi !
Sorry for the slow response time :(

You should use the configuration APP_VERSION 
in that case: 

    https://flask-monitoringdashboard.readthedocs.io/en/latest/configuration.html#the-content-of-the-configuration-file

It takes any string, so you can put in there the 
commit hash from git or some other version 
number that you might have. 

I do something similar here: 

     https://github.com/zeeguu-ecosystem/Lineup/blob/c8f55f93a7fe9d2fbb9bb2e6efcacea31806da04/docker-files/zeeguu-api-core/Dockerfile#L59-L62

I hope this helps.

Cheers,
M.

**Comment by alessiosavi** [comment]
Many thanks! So is already implemented! Issue solved!
