### ISSUE TITLE
Ordering of commits is broken

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#336]
![Screen Shot 2020-05-23 at 12 52 33 PM](https://user-images.githubusercontent.com/464519/82728989-4b72f600-9cf4-11ea-9643-32f8b1a3575a.png)

seems to be alphabetical based on the hash instead of chronological.

this happens (at least) in:
- Per-Version Performance 
- Multi-Version API Utilization

**Comment by bogdanp05** [comment]
Found the cause. It's here: https://github.com/flask-dashboard/Flask-MonitoringDashboard/blob/4ee9d333d6f38b75e6e697c57f470f3d8dbea510/flask_monitoringdashboard/database/versions.py#L6

Should the newest commits appear at the top or at the bottom?

**Comment by mircealungu** [comment]
Nice! I think at the top sounds right.
