### ISSUE TITLE
configuration environment variables for database

### ISSUE THREAD

**Issue by ezeagwulae** [flask-dashboard/Flask-MonitoringDashboard#344]
Any suggestions to go about setting different environment variables especially for database? 

Right now it seems to be fixed string from the config file. Ideally, it'd be great to specify a database to use based on environments (dev or prod) or specify the config file to be used based on based on Flask Config class.

Open to how others have gone about this.

**Comment by FlyingBird95** [comment]
Hey, 

Thanks for your concern. Currently, there are three ways to do the configuration:
- using a configuration file: `dashboard.config.init_from(file='/<path to file>/config.cfg')`
- using an environment variable that points to the configuration file: `dashboard.config.init_from(envar='SOME_VAR')`
- setting the values in de code directly: `dashboard.config.username = 'admin2'`.

Therefore, I think that there are enough ways to configure your FMD. Feel free to send a PR with another way, but I don't think that this is necessary.

Kind regards,

Patrick

**Comment by bogdanp05** [comment]
Just to add on @FlyingBird95's answer, you could do `dashboard.config.database_name = os.environ.get('FMD_DB_NAME')` and it's up to you how to set that env var.

**Comment by ezeagwulae** [comment]
that makes sense and thank you. Im aware of the first two options. More so looking for ways to specify which settings to apply based on different flask environments profiles (i.e. testing, development, production, etc). I figured a workaround, albeit a bit verbose. 

thank again. feel free to close issue.

**Comment by ezeagwulae** [comment]
that would do it @bogdanp05 thanks.
