### ISSUE TITLE
The `use_scm_version` option breaks `setup.py develop`

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#345]
I have added the FMD as a submodule in another project.
This means that it does not have the `.git` folder locally.

Running `setup.py develop` fails because it can't find the .git folder. 

Do we really need the `use_scm_version` option in the setup.py? 

  See: https://github.com/flask-dashboard/Flask-MonitoringDashboard/blob/942e35e79604437d0a588ca4e59eb7be4de1851e/setup.py#L25

The version is already defined in the preceding line.

Thus, unless there's a reason that I don't see for that option, I'd propose that we remove it.

thanks.

**Comment by FlyingBird95** [comment]
Yeah, let's remove it :+1:

**Comment by mircealungu** [comment]
fixed in ea495b662220310ea14d7faa3ffcd6b933a2b034
