### ISSUE TITLE
Can I use environmental variables in config file?

### ISSUE THREAD

**Issue by pycckuu** [flask-dashboard/Flask-MonitoringDashboard#350]
Hello

I was wondering if I can use environmental variables in the config file. For example, I would like to set the path to the database as follows:

`DATABASE=sqlite:////$MY_PATH/db/flask_dashboard.db`

**Comment by mircealungu** [comment]
hi @pycckuu.
config files are meant to be read with [Configparser](https://docs.python.org/3/library/configparser.html). 

Environment variable extensions are not part of that format.

**Comment by pycckuu** [comment]
Ok! I see, thanks for the reply!
