### ISSUE TITLE
Dashboard title problem

### ISSUE THREAD

**Issue by felipecerda** [flask-dashboard/Flask-MonitoringDashboard#351]
Hello,

I just deployed the dashboard on my hosting account and I noticed that the title of the dashboard changed from what I had before. See screenshot below. I do not know what that is, but when I run it locally, the title says "Flask Monitoring Dashboard".

Where is the dashboard getting the title from?

![image](https://user-images.githubusercontent.com/735034/85629184-adb37380-b671-11ea-97be-341eac508447.png)

**Comment by mircealungu** [comment]
Hi @felipecerda !

That's a funny situation.

As far as I can see the master branch of the FMD has a hardcoded string there:

    https://github.com/flask-dashboard/Flask-MonitoringDashboard/blob/0404b05b9a8f1917796e0f314a77a53a754a0b15/flask_monitoringdashboard/templates/fmd_base.html#L24

How did you install the FMD? 

M.

**Comment by mircealungu** [comment]
If you installed it with pip then it's not possible
that the strange text is in the code. 

You can try to change the code in 

<python environment folder>/lib/python3.6/site-packages/flask_monitoringdashboard/templates/fmd_base.html

But I wonder whether the title text is changed later.

Where are you hosting? 
Can you give me the link to the dashboard so I can see this in action?

**Comment by felipecerda** [comment]
@mircealungu Sure, where can I send you the credentials to login?
I am hosting in namecheap.com

**Comment by mircealungu** [comment]
Mlun@itu. Dk
