### ISSUE TITLE
Logs lost on new deployment

### ISSUE THREAD

**Issue by Rolstenhouse** [flask-dashboard/Flask-MonitoringDashboard#365]
**Describe the bug**
Deployed server overwrites past logs with every fresh git deploy

**To Reproduce**
1. Install monitoring dahsboard
2. Run flask on local dev machine
3. Commit files to git (as well as the .db file)
4. Deploy branch to heroku
5. Now added .db file to .gitignore
6. Every subsequent deploy now overwrites log history

**Expected behavior**
Logs kept on production. I'm pretty sure this is something basic I messed up on. Have loved the work you guys are doing so far :)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Deployed with Heroku

**Additional context**
From a business perspective, curious if you guys are considering a playbook similar to the Posthog team (that launched open-source analytics) and are VC backed

**Comment by FlyingBird95** [comment]
Hey Rolstenhouse,

I think that the issue that you describe above is not an FMD issue. It seems that you have trouble with your DB-file, which (in the first place) is a file that you shouldn't commit.

Also, let me explain to you that Heroku dynos (the free ones) are taken offline after they don't receive traffic for 20 minutes. This will also reset the DB. If you want to make use of a proper DB in Heroku, take a look at Heroku Postgres: https://www.heroku.com/postgres

Hopefully this will help you pointing into the right direction.

Kind regards,

Patrick

**Comment by Rolstenhouse** [comment]
Yes! thank you
