### ISSUE TITLE
After logging in not rendering dashboard

### ISSUE THREAD

**Issue by patilgirish815** [flask-dashboard/Flask-MonitoringDashboard#375]
Getting response 302 after logging in. seems redirecturl_for dashboard.index not working

**Comment by mircealungu** [comment]
Hi @patilgirish815 !

Is your code open source? 

Can you create a minimal application that replicates the problem?

M.

**Comment by patilgirish815** [comment]
![IMG_20210303_204156](https://user-images.githubusercontent.com/59241823/109826613-f986d580-7c60-11eb-9302-857a7c17c492.jpg)
After commenting the code in image it works . What can be the reason ? If I uncomment it won't wowork

**Comment by patilgirish815** [comment]
Basically it doesn't works when I load the flask configuration from config.py and in config.py I simply have the other database configurations for my application specific

**Comment by patilgirish815** [comment]
Issue was solved by setting up the flask app config SESSION_COOKIE_SECURE to False.
Is there any dependecy of this flask app config ?
