### ISSUE TITLE
When change the CUSTOM_LINK variable in the configuration css still refers to "dashboard"

### ISSUE THREAD

**Issue by pe2mbs** [flask-dashboard/Flask-MonitoringDashboard#377]
When change the CUSTOM_LINK variable in the configuration css still refers to "dashboard"

In the file static/css/app.css is the 'dashboard/static/fonts/... ' hard coded

**To Reproduce**
Change the CUSTOM_LINK to 'mon-dashboard'
Start the flask application environment
Load the Flask-MonitoringDashboard using http://localhost/mon-dashboard
The console log of the flask application shows
     2021-03-14 08:39:42,361 INFO werkzeug in _internal: 127.0.0.1 - - [14/Mar/2021 08:39:42] "GET /dashboard/static/fonts/fa-solid-900.ttf HTTP/1.1" 404 -

**Expected behavior**
There should not be any hardcoded paths in the app.css

**Comment by mircealungu** [comment]
fixed in https://github.com/flask-dashboard/Flask-MonitoringDashboard/commit/9250f886584fecf3b8227cd4e5fb86dbbc7f859a
