### ISSUE TITLE
Flask-MonitoringDashboard not working at all

### ISSUE THREAD

**Issue by SLey3** [flask-dashboard/Flask-MonitoringDashboard#392]
I tried to use the dashboard but came across 3 problems.

1) When I entered the url that was for the dashboard, I got redirected to my 404 page and instead still uses the old url that I did not config at all.

2) It does not seem to be respecting my config values:
Problems 1 and 3 seem to originate from this problem. as stated in problem 1, it is still using the default url for the dashboard and it also did not seem to respect the username and password that I set in the config file leading me to believe that either I made typos in my config file or that something went wrong when it parsed the config file.

3) It created a separate database from the database I had configured in the config file. 

config file code (for my purposes, I will star the values under the authentication section):
```
[dashboard]
APP_VERSION=1.0
GIT=.git/
CUSTOM_LINK=monitor
SAMPLING_PERIOD=30
ENABLE_LOGGING=True

[authentication]
USERNAME=****
PASSWORD=****

[database]
TABLE_PREFIX=monitor
DATABASE=sqlite:///ProjectsWebsite/database/monitor.db

[visualization]
TIMEZONE=America/Los_Angeles
COLOR={'main':'[0,97,255]',
       'static':'[255,153,0]'}
```
python file (if it helps):
```python
import flask_monitoringdashboard as MonitorDashboard
MonitorDashboard.config.init_from(file='../monitor_config.cfg')
MonitorDashboard.bind(app)
```

**Comment by SLey3** [comment]
Fixed the Issue.

**Comment by iamharky** [comment]
Hi @SLey3 How you made it work?
