### ISSUE TITLE
Flask Monitoring Dashboard in Kubernetes recreates DB on persistent volume for each pod

### ISSUE THREAD

**Issue by codeandmedia** [flask-dashboard/Flask-MonitoringDashboard#406]
**Describe the bug**
Hi Flask Monitoring Dashboard Team! Thanks for your awesome project! I had tried to add Flask Monitoring Dashboard to Kubernetes deployment and faced the issue when DB is placed on persistent volume. Each pod in deployment tries to recreate the DB.

**To Reproduce**
1. Add Flask Monitoring Dashboard to Kubernetes deployment
2. config
```
  config.cfg: |-
    [authentication]
    USERNAME=dashboard
    PASSWORD=protect@dashboard

    [database]
    TABLE_PREFIX=fmd
    DATABASE=sqlite:///storage/dashboard.db

    [visualization]
    TIMEZONE=America/New_York
```
3. /storage -- persistent volume shared for each pod in the deployment 

**Expected behavior**
Ability to add some pod-name to table DB or maybe different way to create and share DB between a couple of replicas of Flask Monitoring Dashboard 

**Screenshots**
![image](https://user-images.githubusercontent.com/59285587/133851648-14ab8d27-5e71-4698-b7f5-5f226a349118.png)

**Desktop (please complete the following information):**
 - Kubernetes

**Comment by mircealungu** [comment]
Hi @codeandmedia! nice to hear that you find FMD useful.
I'm not sure what's the problem.
I also don't use K8s so I can't replicate the problem.

Hopefully somebody else who has more experience with it 
can chip in with a hint.

In the meantime, can you share more from the stack trace?

**Comment by codeandmedia** [comment]
Hi @mircealungu ! Thanks for your message. Looks like the issue here is I have 7 replicas of the app, and all 7 replicas are trying to write in the same table on SQL-lite DB, but the table is locked by first replica. Is it make sense? I have an idea to have for each replica different table inside SQL DB
