### ISSUE TITLE
Extension breaks with Sessions

### ISSUE THREAD

**Issue by bauerem** [flask-dashboard/Flask-MonitoringDashboard#431]
**Describe the bug**
The extension does not work with Flask Sessions. Or if it does work, it is not explained in the documentation how to make it work anyway.

**To Reproduce**
With the Flask app defined as
```
from flask import Flask, session
import flask_monitoringdashboard as dashboard
from flask_session import Session

app = Flask(__name__)
sess = Session()
sess.init_app(app)
dashboard.bind(app)

if __name__=="__main__":
    app.run(debug=True)
```

**Expected behavior**
go to [](http://localhost:5000/dashboard) and login with u: admin, pw: admin.
This yields an error.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox

**Comment by mircealungu** [comment]
If you use flask_session you need to set the secret key.
Your example becomes: 

```
from flask import Flask, session
import flask_monitoringdashboard as dashboard
from flask_session import Session


app = Flask(__name__)

app.secret_key = 'super secret key'
app.config['SESSION_TYPE'] = 'filesystem'

sess = Session()
sess.init_app(app)


dashboard.bind(app)

if __name__=="__main__":
    app.run(debug=True)

```
