### ISSUE TITLE
Flask Dashboard not working, just screen loading and loading

### ISSUE THREAD

**Issue by leetanshaj** [flask-dashboard/Flask-MonitoringDashboard#435]
**Screenshots**
<img width="1574" alt="Screenshot 2023-09-21 at 6 49 39 PM" src="https://github.com/flask-dashboard/Flask-MonitoringDashboard/assets/52253745/689b81cb-94cc-468f-925c-fc4a92e99a81">

What do I do here, facing this on my macOs, ubuntu20.04 with python3.8 python3.10 python3.9 and flask==2.2.3

**Comment by mircealungu** [comment]
Do you see any errors in the terminal or the logs? It seems like the dashboard is not finding your endpoints. Is your codebase open-source. Alternatively can you isolate the minimum code that replicates the issue?

**Comment by leetanshaj** [comment]
1. I've tried with a very basic app, it's not working
app=Flask(__name__)
@app.route('/test')
def kk():
    return {"ok":1}
    
2. No error in terminal, I've even turned on logging by dashboard.config.enable_logging=True, no error there
3. I checked the .db file, it contains table but table does not contain any row

**Comment by mircealungu** [comment]
I'm missing the FMD `bind` call. Where do you do that?

**Comment by leetanshaj** [comment]
`import flask_monitoringdashboard as dashboard
from flask import Flask

app = Flask(__name__)
dashboard.config.enable_logging=True
dashboard.bind(app)


@app.route("/test", methods = ['GET'])
def kk():
	return {"ok": True}


app.run()`

**Comment by mircealungu** [comment]
ehi @leetanshaj .

altthough i didn't remember this being necessary, it seems that you have to run `dashboard.bind` after all the app routes have been defined. can you check that this code works for you?

```
import flask_monitoringdashboard as dashboard
from flask import Flask

app = Flask("name")


@app.route("/test", methods = ['GET'])
def kk():
	return {"ok": True}

dashboard.config.enable_logging=True
dashboard.bind(app)

app.run()
```

**Comment by leetanshaj** [comment]
Thanks man! It works

**Comment by mat-l** [comment]
Can confirm that "dashboard.bind(app)" must be executed after the routes.
