### ISSUE TITLE
wasteful use of the best real estate space with  the "summary of endpoint"

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#63]
that info is less relevant than the actual graphs, but takes the best
real estate. better move it to the bottom instead if we still decide to keep it. 

![screenshot 2018-03-18 14 18 11](https://user-images.githubusercontent.com/464519/37566281-4591c63c-2ab7-11e8-8aff-fc590b50daa5.png)

**Comment by FlyingBird95** [comment]
Fixed in version 1.12.0
