### ISSUE TITLE
ordering of the "graphs" is quite random and so are their names...

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#64]
ordering should  should start from the most interesting view to the least interesting
probably: 
- Time per Version 
- Heatmap 

Some of the more experimental ones might even be hid by default...e.g. time per ip... 

also, the naming is not principled:
- time per version -- what is being shown
- heatmap -- how is the stuff being shown (we don't even know what)

**Comment by mircealungu** [comment]
One thing that we must do ASAP is to bring the names of the graphs in sync with the names we presented in the ICSME paper. In case somebody tries the dashboard while reading the paper, they should be able to find the views that are mentioned there. 

Also, we should really sit together and decide which views we show by default and hide some. Less is more, and currently we have too many views, and not all are equally useful.

**Comment by bogdanp05** [comment]
Fixed in #126
