### ISSUE TITLE
opt-in / opt-out

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#72]
for testing reasons, but also in general i started to think that it could make sense to provide a config option which would allow one to set the default state of all the endpoints. 

now they are by default not tracked, and one can choose to opt-in to the ones they want to track. 

a config option that would allow setting the default state of an endpoint might be good also for evolution analysis. now, if you rename an endpoint, you have to remember to start tracking the new one. if they would all be tracked by default, this would not be needed.

what do you think?

option could be: 

    default_track = [True | False]

**Comment by mircealungu** [comment]
would have been handy to have also for your API tests methinks, @FlyingBird95

**Comment by FlyingBird95** [comment]
Implemented in v1.13.0
