### ISSUE TITLE
blue_print should be blueprint

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#75]
e.g. here: https://github.com/zeeguu-ecosystem/Zeeguu-API/blob/master/zeeguu_api/app.py#L43

also, by default all the blueprints should be monitored. 
thus the binding should be achievable with only: 

    dash.bind(app)

**Comment by kloostert** [comment]
All blueprints of the user app are now monitored w.r.t. unit tests by default, which means the binding can be achieved again by only:
`dashboard.bind(app)`
