### ISSUE TITLE
refactor the group_by 

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#80]
such that it matches the API presented in the paper.
most importance changes: shorten the name of the config option and take the name of the category as the first element in the tuple

```
# LOC #2: configure the dashboard
# to group requests by the user id
dashboard.config.group_by = 'User',
	lambda: Session.find(flask.request).user.id
```

**Comment by FlyingBird95** [comment]
Fixed since version 1.12.0
