### ISSUE TITLE
allow time period selection for every view

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#82]
this would be good to have for the CR ready version of the paper. 
should be quite straightforward. 

and would allow us to regenerate some of the older graphs with the new colors. which would make the paper even more awesome than it is now!

**Comment by mircealungu** [comment]
as inspiration we should take the Period selector from GitHub: 

    https://github.com/flask-dashboard/Flask-MonitoringDashboard/pulse

with an extra version where we can select any specific time range.

**Comment by FlyingBird95** [comment]
Fixed since version 1.12.0
