### ISSUE TITLE
Outlier Visualization: summarizing CPU load

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#86]
it would be good to see at a glance an overview of all the CPU loads corresponding to these outliers

**Comment by bogdanp05** [comment]
I implemented a simple function that shows at the beginning of the outliers list the mean CPU % for all the outliers of that endpoint. Another option would be to show a mean value per CPU core, although if the app is deployed at some moment on a machine with a different number of cores, that wouldn't make much sense.
![selection_128](https://user-images.githubusercontent.com/7281856/39121448-f496fc3c-46f1-11e8-8cad-31d8829152e5.png)

**Comment by mircealungu** [comment]
Per core is better.
I don't think we should worry too much about people changing servers. We've
been running zeeguu on the same server for two years..

**Comment by bogdanp05** [comment]
Ok. I updated the method and now it looks like this:
![selection_130](https://user-images.githubusercontent.com/7281856/39188455-26c3e60a-47d0-11e8-9611-f54a76729306.png)
I'll do a commit.

**Comment by mircealungu** [comment]
Looks good.
Maybe round to the closes integer?

M.

**Comment by mircealungu** [comment]
When you're done with this, send PR to master
and let's deploy it so we can have a look at the
various endpoints!

M.

**Comment by bogdanp05** [comment]
Done.
![selection_131](https://user-images.githubusercontent.com/7281856/39189066-a3578400-47d1-11e8-8adf-73ba534d23d2.png)

**Comment by bogdanp05** [comment]
I updated the Outliers page to show boxplots of the loads of the different CPU cores. Should I also keep the **Mean CPU Percentage** info or discard it? These changes were implemented in db1f0f22bb70a13035968c6fc92e73b62d458b30 .
![selection_150](https://user-images.githubusercontent.com/7281856/39820912-4270b044-53a7-11e8-996a-36e30d127bd2.png)

**Comment by mircealungu** [comment]
Looks nice @bogdanp05 ! 
I guess you can discard the mean text... the means are visible on the graphic.
